/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-09-27 06:55:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("   <script type=\"text/javascript\" language=\"javascript\" src=\"https://www.technicalkeeda.com/js/javascripts/plugin/jquery.js\"></script>\n");
      out.write("   <script type=\"text/javascript\" src=\"https://www.technicalkeeda.com/js/javascripts/plugin/json2.js\"></script>\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("   <title>Spring Jquery Ajax Demo</title>\n");
      out.write("   <style>\n");
      out.write("      Table.GridOne {\n");
      out.write("      padding: 3px;\n");
      out.write("      margin: 0;\n");
      out.write("      background: lightyellow;\n");
      out.write("      border-collapse: collapse; \n");
      out.write("      width:35%;\n");
      out.write("      }\n");
      out.write("      Table.GridOne Td { \n");
      out.write("      padding:2px;\n");
      out.write("      border: 1px solid #ff9900;\n");
      out.write("      border-collapse: collapse;\n");
      out.write("      }\n");
      out.write("   </style>\n");
      out.write("   <script type=\"text/javascript\">\n");
      out.write("      function madeAjaxCall(){\n");
      out.write("       $.ajax({\n");
      out.write("        type: \"post\",\n");
      out.write("        url: \"http://localhost:8080/tommystore/add\",\n");
      out.write("        cache: false,    \n");
      out.write("        data:'firstName=' + $(\"#firstName\").val() + \"&lastName;=\" + $(\"#lastName\").val() + \"&email;=\" + $(\"#email\").val(),\n");
      out.write("        success: function(response){\n");
      out.write("         $('#result').html(\"\");\n");
      out.write("         var obj = JSON.parse(response);\n");
      out.write("         $('#result').html(\"First Name:- \" + obj.firstName +\"</br>Last Name:- \" + obj.lastName  + \"</br>Email:- \" + obj.email);\n");
      out.write("        },\n");
      out.write("        error: function(){      \n");
      out.write("         alert('Error while request..');\n");
      out.write("        }\n");
      out.write("       });\n");
      out.write("      }\n");
      out.write("   </script>\n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("      <form name=\"employeeForm\" method=\"post\">\n");
      out.write("         <table cellpadding=\"0\" cellspacing=\"0\" border=\"1\" class=\"GridOne\">\n");
      out.write("            <tr>\n");
      out.write("               <td>First Name</td>\n");
      out.write("               <td><input type=\"text\" name=\"firstName\" id=\"firstName\" value=\"\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <td>Last Name</td>\n");
      out.write("               <td><input type=\"text\" name=\"lastName\" id=\"lastName\" value=\"\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <td>Email</td>\n");
      out.write("               <td><input type=\"text\" name=\"email\" id=\"email\" value=\"\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <td colspan=\"2\" align=\"center\"><input type=\"button\" value=\"Ajax Submit\" onclick=\"madeAjaxCall();\"></td>\n");
      out.write("            </tr>\n");
      out.write("         </table>\n");
      out.write("      </form>\n");
      out.write("      <h1>Spring Framework Jquery Ajax Demo</h1>\n");
      out.write("      <div id=\"result\"></div>\n");
      out.write("   </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
